export const puppyQuotes = [
  'Everything is not going to be not okay.',
  'Whelp',
  "You're doing okay. Middle of the road I suppose.",
  'Life, huh? Weird.',
  'You certainly are a person.',
  'Only 30 more years.',
  'Another day, another existential crisis.',
  "You're not the worst.",
  "Keep on keepin' on",
  '...sigh...',
  "You're doing great, sweetie.",
  '🙃',
  '😬',
  '🤷‍♀️',
  '🫠',
  'Never put off until tomorrow what you can do the day after tomorrow.',
  'Every dead body on Mt. Everest was once a highly motivated person, so… maybe calm down.',
  'When life knocks you down, stay there and take a nap.',
  'Your life can’t fall apart if you never had it together.',
  'You’re naturally funny because your life is a joke.',
  'ℑ𝔱 𝔦𝔰 𝔫𝔢𝔳𝔢𝔯 𝔱𝔬𝔬 𝔩𝔞𝔱𝔢 𝔱𝔬 𝔤𝔦𝔳𝔢 𝔲𝔭.',
  'It may be that the purpose of your life is to serve as a warning for others.',
  'Live slow. Die whenever.',
  'Trying is the first step to failure.',
  'Don’t just be a part of the problem. Be the whole problem.',
  'Remember: this is just the worst day of your life so far...',
  'You will never fail if you never try',
  'Don"t just dream your dreams. Sleep through them',
  'Remember: even if you are unique, you are probably not useful',
  'The glass is not half empty or half full. It is just another glass you have to wash',
  'Could be worse. Could also be significantly better',
  'Just... keep breathing, I guess',
  'You are managing to occupy space. Well done',
  '𝕊𝕦𝕣𝕧𝕚𝕧𝕚𝕟𝕘, 𝕟𝕠𝕥 𝕥𝕙𝕣𝕚𝕧𝕚𝕟𝕘',
  'You are definitely in the top 8 billion people I know',
  'Hmmmmmm',
  'Another day to aim low and mostly hit the mark. Or not. Whatever',
  '-insert quote here-',
  '🍻',
  '🫥',
  '🤡',
  '💩',
  '^_____^',
  '<@_@>',
  'Optimism never gets you far',
  'When life gives you lemons, throw them at people you hate',
  'Hang in there 😿',
  'The only way to succeed in life is to always feel like a failure ~ Madi 2025',
  'Live fast die young bad girls do it well',
  '𝐘𝐨𝐮 𝐚𝐫𝐞 𝐚 𝐛𝐚𝐜𝐤𝐠𝐫𝐨𝐮𝐧𝐝 𝐜𝐡𝐚𝐫𝐚𝐜𝐭𝐞𝐫 𝐢𝐧 𝐚 𝐦𝐮𝐜𝐡 𝐦𝐨𝐫𝐞 𝐢𝐧𝐭𝐞𝐫𝐞𝐬𝐭𝐢𝐧𝐠 𝐩𝐞𝐫𝐬𝐨𝐧"𝐬 𝐬𝐭𝐨𝐫𝐲',
  '🇹🇭🇮🇸  🇶🇺🇴🇹🇪  🇼🇦🇸  🇮🇳🇹🇪🇳🇹🇮🇴🇳🇦🇱🇱🇾  🇱🇪🇫🇹  🇧🇱🇦🇳🇰',
  '𝘛𝘩𝘦 𝘦𝘢𝘳𝘭𝘺 𝘸𝘰𝘳𝘮 𝘨𝘦𝘵𝘴 𝘦𝘢𝘵𝘦𝘯.',
  'C̞̞̼̀͋a̗̺̍̍̄n̯̥̩̼ͤ y͇͓ͭo̖͉̬̯͗̋̉̽u̮ͩ̇ e̤̍ͦ̚ͅṿ̈e͉̔̒n̮͚͎͙̆͆ͨͭ r̗̗ͩ̏ͧè͔̲̙̊̄a̠̬ͧ̐d̘̥ͣ ț̭͙̈̉h̥̹̙́ͥȋ̮̟͔ͅs̥͒ͫͨ?̤̙̒͂͐̚',
  '01010010 01101111 01100010 01101111 01110100 01110011 00100000 01110111 01101001 01101100 01101100 00100000 01110010 01100101 01110000 01101100 01100001 01100011 01100101 00100000 01110101 01110011 00100000 01100001 01101100 01101100 00101110',
  '⠺⠁⠊⠞⠂⠀⠺⠓⠕⠀⠞⠥⠗⠝⠑⠙⠀⠕⠥⠞⠀⠞⠓⠑⠀⠇⠊⠛⠓⠞⠎⠦',
  'Ｈ ｏ ｐ ｅ    ｉ ｓ    ｔ ｈ ｅ    ｆ ｉ ｒ ｓ ｔ    ｓ ｔ ｅ ｐ    ｏ ｎ    ｔ ｈ ｅ    ｒ ｏ ａ ｄ    ｔ ｏ    ｄ ｉ ｓ ａ ｐ ｐ ｏ ｉ ｎ ｔ ｍ ｅ ｎ ｔ ．',
  '˙uʍop ǝpᴉsdn ǝq ʎɐɯ noʎ sᴉɥʇ ƃuᴉpɐǝɹ ǝɹ,noʎ ɟI',
  '🇸🇴🇲🇪🇹🇮🇲🇪🇸  🇹🇭🇪  🇴🇳🇱🇾  🇨🇭🇴🇮🇨🇪🇸  🇱🇪🇫🇹  🇦🇷🇪  🇧🇦🇩  🇴🇳🇪🇸.',
];
